/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hello.app;

import io.molr.commons.domain.StrandCommand;
import io.molr.mole.core.single.SingleNodeMission;
import io.molr.mole.core.single.SingleNodeMissionExecutor;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;

public class App {

    private static final String defaultName = "Himanshu";

    public SingleNodeMission<Void> helloWorld() {
        return SingleNodeMission.from(() -> {
            System.out.println("Hello World");
        }).withName("hello-world");
    }

    public SingleNodeMission<Void> helloName(String name) {
        return SingleNodeMission.from(() -> {
            System.out.println("Hello " + name);
        }).withName("hello-name");
    }


    public static void main(String[] args) {
        String name;
        if (args.length > 0) {
            name = args[0];
        } else {
            name = defaultName;
        }
        List<SingleNodeMissionExecutor> executors = new ArrayList<>();
        executors.add(new SingleNodeMissionExecutor(new App().helloWorld(), new HashMap<>()));
        executors.add(new SingleNodeMissionExecutor(new App().helloName(name), new HashMap<>()));
        for (SingleNodeMissionExecutor executor : executors) {
            executor.instructRoot(StrandCommand.RESUME);
        }
    }
}
